filters:
  - label: feat
    regexs:
      - /^feat:\s/
    events: [issues, pull_request]
    targets: [title]

  - label: fix
    regexs:
      - /^fix:\s/
    events: [issues, pull_request]
    targets: [title]

  - label: hotfix
    regexs:
      - /^hotfix:\s/
    events: [issues, pull_request]
    targets: [title]

  - label: docs
    regexs:
      - /^docs:\s/
    events: [issues, pull_request]
    targets: [title]

  - label: style
    regexs:
      - /^style:\s/
    events: [issues, pull_request]
    targets: [title]

  - label: refactor
    regexs:
      - /^refactor:\s/
    events: [issues, pull_request]
    targets: [title]

  - label: test
    regexs:
      - /^test:\s/
    events: [issues, pull_request]
    targets: [title]

  - label: chore
    regexs:
      - /^chore:\s/
    events: [issues, pull_request]
    targets: [title]

  - label: infra
    regexs:
      - /^infra:\s/
    events: [issues]
    targets: [title]
