filters:
  - label: feat
    regexs:
      - /^feat\s*:\s*/
    events: [issues, pull_request]
    targets: [title]

  - label: fix
    regexs:
      - /^fix\s*:\s*/
    events: [issues, pull_request]
    targets: [title]

  - label: hotfix
    regexs:
      - /^hotfix\s*:\s*/
    events: [issues, pull_request]
    targets: [title]

  - label: docs
    regexs:
      - /^docs\s*:\s*/
    events: [issues, pull_request]
    targets: [title]

  - label: style
    regexs:
      - /^style\s*:\s*/
    events: [issues, pull_request]
    targets: [title]

  - label: refactor
    regexs:
      - /^refactor\s*:\s*/
    events: [issues, pull_request]
    targets: [title]

  - label: test
    regexs:
      - /^test\s*:\s*/
    events: [issues, pull_request]
    targets: [title]

  - label: chore
    regexs:
      - /^chore\s*:\s*/
    events: [issues, pull_request]
    targets: [title]

  - label: infra
    regexs:
      - /^infra\s*:\s*/
    events: [issues]
    targets: [title]
