filters:
  - label: feat
    regexs:
      - /^feat\b/
    events: [issues, pull_request]
    targets: [title]

  - label: fix
    regexs:
      - /^fix\b/
    events: [issues, pull_request]
    targets: [title]

  - label: hotfix
    regexs:
      - /^hotfix\b/
    events: [issues, pull_request]
    targets: [title]

  - label: docs
    regexs:
      - /^docs\b/
    events: [issues, pull_request]
    targets: [title]

  - label: style
    regexs:
      - /^style\b/
    events: [issues, pull_request]
    targets: [title]

  - label: refactor
    regexs:
      - /^refactor\b/
    events: [issues, pull_request]
    targets: [title]

  - label: test
    regexs:
      - /^test\b/
    events: [issues, pull_request]
    targets: [title]

  - label: chore
    regexs:
      - /^chore\b/
    events: [issues, pull_request]
    targets: [title]

  - label: infra
    regexs:
      - /^infra\b/
    events: [issues]
    targets: [title]
